format = """
[](#C71585)\
$python\
$username\
[](bg:#F4C2C2 fg:#3A0E1A)\
$directory\
[](fg:#F4C2C2 bg:#FF69B4)\
$git_branch\
$git_status\
[](fg:#FF69B4 bg:#FF1493)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#FF1493 bg:#FFB6C1)\
$docker_context\
[](fg:#FFB6C1 bg:#FFC0CB)\
$time\
[ ](fg:#FFC0CB)\
"""

command_timeout = 5000

[username]
show_always = true
style_user = "bg:#C71585 fg:#FFFFFF"
style_root = "bg:#C71585 fg:#FFFFFF"
format = '[$user ]($style)'

[directory]
style = "bg:#F4C2C2 fg:#3A0E1A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#FFB6C1 fg:#3A0E1A"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FF69B4 fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FF69B4 fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#C71585 fg:#FFFFFF"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#FF1493 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#FFC0CB fg:#3A0E1A"
format = '[ $time ]($style)'
