format = """
[](#F4C2C2)\
$python\
$username\
[](bg:#E6A9A9 fg:#F4C2C2)\
$directory\
[](fg:#E6A9A9 bg:#F7D1D1)\
$git_branch\
$git_status\
[](fg:#F7D1D1 bg:#F9B7B7)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#F9B7B7 bg:#F4C2C2)\
$docker_context\
[](fg:#F4C2C2 bg:#F4C2C2)\
$time\
[ ](fg:#F4C2C2)\
"""

command_timeout = 5000

[username]
show_always = true
style_user = "bg:#F4C2C2"
style_root = "bg:#F4C2C2"
format = '[$user ]($style)'

[directory]
style = "bg:#E6A9A9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#F9B7B7"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#F7D1D1"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F7D1D1"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#F4C2C2"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#F7D1D1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#F4C2C2"
format = '[ $time ]($style)'
